//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnHolliday.Caml.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JohnHolliday.Caml.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHyperLink.
        /// </summary>
        public static string AutoHyperLink {
            get {
                return ResourceManager.GetString("AutoHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHyperLinkNoEncoding.
        /// </summary>
        public static string AutoHyperLinkNoEncoding {
            get {
                return ResourceManager.GetString("AutoHyperLinkNoEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoNewLine.
        /// </summary>
        public static string AutoNewLine {
            get {
                return ResourceManager.GetString("AutoNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginsWith.
        /// </summary>
        public static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypeId.
        /// </summary>
        public static string ContentTypeId {
            get {
                return ResourceManager.GetString("ContentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentUserGroups.
        /// </summary>
        public static string CurrentUserGroups {
            get {
                return ResourceManager.GetString("CurrentUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateRangesOverlap.
        /// </summary>
        public static string DateRangesOverlap {
            get {
                return ResourceManager.GetString("DateRangesOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eq.
        /// </summary>
        public static string Eq {
            get {
                return ResourceManager.GetString("Eq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALSE.
        /// </summary>
        public static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldId.
        /// </summary>
        public static string FieldId {
            get {
                return ResourceManager.GetString("FieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldRef.
        /// </summary>
        public static string FieldRef {
            get {
                return ResourceManager.GetString("FieldRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geq.
        /// </summary>
        public static string Geq {
            get {
                return ResourceManager.GetString("Geq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBy.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gt.
        /// </summary>
        public static string Gt {
            get {
                return ResourceManager.GetString("Gt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTMLEncode.
        /// </summary>
        public static string HTMLEncode {
            get {
                return ResourceManager.GetString("HTMLEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeTimeValue.
        /// </summary>
        public static string IncludeTimeValue {
            get {
                return ResourceManager.GetString("IncludeTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNotNull.
        /// </summary>
        public static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNull.
        /// </summary>
        public static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leq.
        /// </summary>
        public static string Leq {
            get {
                return ResourceManager.GetString("Leq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupId.
        /// </summary>
        public static string LookupId {
            get {
                return ResourceManager.GetString("LookupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt.
        /// </summary>
        public static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neq.
        /// </summary>
        public static string Neq {
            get {
                return ResourceManager.GetString("Neq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable.
        /// </summary>
        public static string Nullable {
            get {
                return ResourceManager.GetString("Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetDays.
        /// </summary>
        public static string OffsetDays {
            get {
                return ResourceManager.GetString("OffsetDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderBy.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectProperty.
        /// </summary>
        public static string ProjectProperty {
            get {
                return ResourceManager.GetString("ProjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPGroup.
        /// </summary>
        public static string SPGroup {
            get {
                return ResourceManager.GetString("SPGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.AllUsers.
        /// </summary>
        public static string SPWebAllUsers {
            get {
                return ResourceManager.GetString("SPWebAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.Groups.
        /// </summary>
        public static string SPWebGroups {
            get {
                return ResourceManager.GetString("SPWebGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPWeb.Users.
        /// </summary>
        public static string SPWebUsers {
            get {
                return ResourceManager.GetString("SPWebUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StripWS.
        /// </summary>
        public static string StripWS {
            get {
                return ResourceManager.GetString("StripWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodayISO.
        /// </summary>
        public static string TodayISO {
            get {
                return ResourceManager.GetString("TodayISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        public static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLEncode.
        /// </summary>
        public static string URLEncode {
            get {
                return ResourceManager.GetString("URLEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLEncodeAsURL.
        /// </summary>
        public static string URLEncodeAsURL {
            get {
                return ResourceManager.GetString("URLEncodeAsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewFields.
        /// </summary>
        public static string ViewFields {
            get {
                return ResourceManager.GetString("ViewFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webs.
        /// </summary>
        public static string Webs {
            get {
                return ResourceManager.GetString("Webs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithIndex.
        /// </summary>
        public static string WithIndex {
            get {
                return ResourceManager.GetString("WithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
